# Generated by Django 5.1.3 on 2024-11-14 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankBalances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetCurrentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odsecurity_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('odusage_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='OverdraftDetail',
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='netcurrentasset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankBalances.currency'),
        ),
    ]
