# Generated by Django 5.1.3 on 2024-11-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankBalances', '0002_netcurrentasset_delete_overdraftdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='currentasset',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='netcurrentasset',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.RemoveField(
            model_name='unutilizedgrant',
            name='currency',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='bankbalance',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankBalances.currency'),
        ),
        migrations.DeleteModel(
            name='CurrentAsset',
        ),
        migrations.DeleteModel(
            name='NetCurrentAsset',
        ),
        migrations.DeleteModel(
            name='UnutilizedGrant',
        ),
    ]
